hyundai-autoever-second-project-team4/Review-BE

ddl/movie.sql, ddl/review.sql, src/main/java/hyundai/movie_review/movie/entity/Movie.java, src/main/java/hyundai/movie_review/movie/exception/MovieIdNotFoundException.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepository.java, src/main/java/hyundai/movie_review/review/exception/ReviewAlreadyExistsException.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepository.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java, src/test/java/hyundai/movie_review/review/service/ReviewServiceTest.java
- close #9 
> Movie 엔티티 구현
리뷰 생성 시, movie 엔티티에 해당하는 total values 값 증가 구현
리뷰 삭제 시, movie 엔티티에 해당하는 total values 값 감소 구현
리뷰 생성, 삭제에 대한 `ReviewService` 단에 대한 `Unit Test (with mock)` 구현
>
=> Movie review/#9

src/main/java/hyundai/movie_review/badge/entity/Badge.java, src/main/java/hyundai/movie_review/badge/exception/BadgeIdNotFoundException.java, src/main/java/hyundai/movie_review/member/entity/Member.java, src/main/java/hyundai/movie_review/member/repository/MemberRepositoryImpl.java, src/main/java/hyundai/movie_review/member_badge/repository/MemberBadgeRepository.java, src/main/java/hyundai/movie_review/security/authentication/CustomUserDetailService.java, src/main/java/hyundai/movie_review/security/model/OAuth2UserInfo.java
=> refactor: Member 구조 수정

src/main/java/hyundai/movie_review/thear_down/controller/ThearDownController.java, src/main/java/hyundai/movie_review/thear_down/dto/ThearDownResponse.java, src/main/java/hyundai/movie_review/thear_down/entity/ThearDown.java, src/main/java/hyundai/movie_review/thear_down/repository/ThearDownRepository.java, src/main/java/hyundai/movie_review/thear_down/service/ThearDownService.java, src/main/java/hyundai/movie_review/thear_up/entity/ThearUp.java, src/main/java/hyundai/movie_review/thear_up/repository/ThearUpRepository.java
close #17 
> ThearDown 개발 완료
> 추후에 리뷰에 대한 로그인한 맴버가 좋아요를 했는지 싫어요를 했는지 boolean 값으로 프론트한테 던져줘야할듯. (영화 상세 페이지에서)
=> theardown 테이블 완료

src/main/java/hyundai/movie_review/member/entity/Member.java
=> refactor: member의 어노테이션 badge 수정

src/main/java/hyundai/movie_review/badge/dto/BadgeInfoDto.java, src/main/java/hyundai/movie_review/member/controller/MemberController.java, src/main/java/hyundai/movie_review/member/dto/MemberInfoResponse.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/tier/dto/TierInfoDto.java
=> feat: member 로그인 정보 엔드 포인트 구현

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: swagger api 명세 수정

src/main/java/hyundai/movie_review/comment/entity/Comment.java, src/main/java/hyundai/movie_review/comment/repository/CommentRepository.java, src/main/java/hyundai/movie_review/comment/service/CommentService.java, src/main/java/hyundai/movie_review/member/entity/Member.java, src/main/java/hyundai/movie_review/movie/controller/MovieController.java, src/main/java/hyundai/movie_review/movie/dto/MovieDetailResponse.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java, src/main/java/hyundai/movie_review/review/dto/ReviewByMovieIdDto.java, src/main/java/hyundai/movie_review/review/dto/ReviewByMovieIdListDto.java, src/main/java/hyundai/movie_review/review/dto/ReviewThearUpDownCheckedDto.java, src/main/java/hyundai/movie_review/review/entity/Review.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepositoryCustom.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepositoryImpl.java, src/main/java/hyundai/movie_review/thear_down/entity/ThearDown.java, src/main/java/hyundai/movie_review/thear_down/repository/ThearDownRepository.java, src/main/java/hyundai/movie_review/thear_down/service/ThearDownService.java, src/main/java/hyundai/movie_review/thear_up/entity/ThearUp.java, src/main/java/hyundai/movie_review/thear_up/repository/ThearUpRepository.java, src/main/java/hyundai/movie_review/thear_up/service/ThearUpService.java
- close #23
영화 상세보기 정보 요청 시, reviewByMovieIdList정보가 추가되어서 전송됩니다. Dto 안에는 각각 reviewList와 reviewThearUpDown이 속해 있습니다.
reviewList에는 멤버 티어, 프로필, 닉네임, 리뷰 별점, 내용, 스포일러 여부, 댓글 개수, thearup, theardown
reviewThearUpDown에는 각 리뷰에 대해 현재 로그인한 멤버가 up down을 체크한 여부를 담고 있습니다.
=> Movie reviews order by like/#23

src/main/java/hyundai/movie_review/movie/controller/MovieController.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustom.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustomImpl.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java, src/main/java/hyundai/movie_review/movie/vo/MovieGenreCountMap.java
=> feat: 사용자가 작성한 리뷰 기반 추천 영화 기능 구현

src/main/java/hyundai/movie_review/movie/controller/MovieController.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustom.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustomImpl.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java
=> feat: 전체 리뷰 중, 가장 리뷰가 많은 영화를 정렬하여 리턴하는 명예의 전당 api 구현

src/main/java/hyundai/movie_review/comment/controller/CommentController.java, src/main/java/hyundai/movie_review/review/controller/ReviewController.java, src/main/java/hyundai/movie_review/thear_down/controller/ThearDownController.java, src/main/java/hyundai/movie_review/thear_up/controller/ThearUpController.java
=> refactor: `@Tag` 어노테이션을 통한 controller 리팩토링

src/main/java/hyundai/movie_review/movie/service/MovieService.java, src/main/java/hyundai/movie_review/review/controller/ReviewController.java, src/main/java/hyundai/movie_review/review/dto/ReviewInfoDto.java, src/main/java/hyundai/movie_review/review/dto/ReviewInfoListDto.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepository.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepositoryCustom.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepositoryImpl.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java
- close #49 
> thearup이 가장 많이 달린 리뷰순으로 조회 기능 구현
>
=> feat: 하루동안 핫한 리뷰들을 가져오는 기능 구현

src/main/java/hyundai/movie_review/review/controller/ReviewController.java
=> refactor: review controller의 200 응답 clas 수정

src/main/java/hyundai/movie_review/badge/dto/BadgeMyPageInfoDto.java, src/main/java/hyundai/movie_review/member/controller/MemberController.java, src/main/java/hyundai/movie_review/member/dto/GetMemberMyPageResponse.java, src/main/java/hyundai/movie_review/member/dto/MemberMyPageInfoDto.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/tier/dto/TierMyPageInfoDto.java
- close #43
> 마이페이지 상단의 프로필 정보를 조회합니다.
=> Mypage profile info/#43

src/main/java/hyundai/movie_review/review/dto/ReviewInfoDto.java
=> refactor: ReviewInfoDto 리턴값에 movie 정보를 주도록 수정

src/main/java/hyundai/movie_review/badge/dto/BadgeMyPageInfoDto.java, src/main/java/hyundai/movie_review/genre/dto/GenreCountDto.java, src/main/java/hyundai/movie_review/genre/dto/GenreCountListDto.java, src/main/java/hyundai/movie_review/genre/repository/GenreRepository.java, src/main/java/hyundai/movie_review/genre/repository/GenreRepositoryCustom.java, src/main/java/hyundai/movie_review/genre/repository/GenreRepositoryImpl.java, src/main/java/hyundai/movie_review/member/dto/GetMemberMyPageResponse.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/tier/dto/TierMyPageInfoDto.java
- close #57
> 마이페이지에서 영화 선호 장르에 해당하는 정보를 조회합니다.
=> feat: 마이페이지 영화 선호 장르 조회

src/main/java/hyundai/movie_review/badge/dto/BadgeMyPageInfoDto.java, src/main/java/hyundai/movie_review/genre/dto/GenreCountDto.java, src/main/java/hyundai/movie_review/member/controller/MemberController.java, src/main/java/hyundai/movie_review/member/dto/GetMemberMyPageResponse.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/review/dto/ReviewCountArrayDto.java
- close #59
> 마이페이지 별점 분포에 필요한 평점 분포 배열, 평균 평점, 전체 평점 개수, 가장 많은 평점을 조회합니다.
=> feat: 마이페이지 별점 조회 기능

src/main/java/hyundai/movie_review/member/dto/GetMemberMyPageResponse.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/review/repository/ReviewRepository.java
- close #63
> 마이페이지에서 사용자가 작성한 리뷰 최신 순으로 5개 조회합니다.
=> feat: 마이페이지 리뷰 최신 순 5개 조회

src/main/java/hyundai/movie_review/security/authentication/JwtAuthenticationFilter.java
=> refactor: request header 리팩토링

src/main/java/hyundai/movie_review/genre/dto/GenreCountDto.java
- close #71
> 마이페이지 별점 분포 데이터 전달 명칭 변경
=> fix: 마이페이지 별점 분포 리팩토링

src/main/java/hyundai/movie_review/review/dto/ReviewCountListDto.java
=> refactor: movie 상세 정보의 별점 정보 업데이트

src/main/java/hyundai/movie_review/badge/dto/BadgeMyPageInfoDto.java
- close #76
마이페이지에서 사용자 배지 리스트에서 대표 배지가 첫번째로 전달됩니다.
=> fix: 마이페이지 사용자 배지 조회 리팩토링

src/main/java/hyundai/movie_review/comment/dto/CommentGetResponse.java, src/main/java/hyundai/movie_review/comment/service/CommentService.java, src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/review/controller/ReviewController.java, src/main/java/hyundai/movie_review/review/dto/ReviewDetailInfoDto.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java
- close #73
리뷰 상세 모달에 필요한 데이터를 조회합니다.
=> feat: 리뷰 상세 모달 조회 구현

src/main/java/hyundai/movie_review/member/service/MemberService.java
- close #81
마이페이지 리뷰 조회에서 up, down 반영 여부 수정
=> fix: 마이페이지 리뷰 조회 기능 수정

src/main/java/hyundai/movie_review/movie/dto/MovieDetailResponse.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java
- close #83
영화 상세페이지 정보 조회 시, 사용자의 리뷰 작성 여부 데이터를 확인할 수 있습니다.
=> feat: 영화 상세페이지 리뷰 작성 여부 확인 데이터 추가

src/main/java/hyundai/movie_review/movie_tag/repository/MovieTagRepository.java, src/main/java/hyundai/movie_review/review/dto/ReviewCreateRequest.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java, src/main/java/hyundai/movie_review/tag/exception/TagIdNotFoundException.java, src/main/java/hyundai/movie_review/tag/repository/TagRepository.java
=> refactor: 리뷰 생성 시, tag id를 전달하여 movie-tag 정보가 저장되도록 구현

src/main/java/hyundai/movie_review/member/service/MemberService.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java, src/main/java/hyundai/movie_review/review/dto/ReviewInfoDto.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java
- close #91
로그인한 사용자가 리뷰 작성자인지 체크한 데이터가 추가됐습니다.
=> feat: 로그인한 사용자가 리뷰 작성자인지 체크

src/main/java/hyundai/movie_review/member/controller/MemberController.java, src/main/java/hyundai/movie_review/member/service/MemberService.java
- close #93
> 유저의 마이페이지 상세 보기 api입니다.
=> feat: 유저의 마이페이지 상세 정보 보기

src/main/java/hyundai/movie_review/review/dto/ReviewInfoDto.java
- close #102
리뷰 조회 데이터 요청 시 멤버의 뱃지 이미지 경로도 제공
=> fix: 뱃지 이미지 전달 추가

src/main/java/hyundai/movie_review/comment/controller/CommentController.java, src/main/java/hyundai/movie_review/comment/dto/CommentGetAllResponse.java, src/main/java/hyundai/movie_review/comment/service/CommentService.java, src/main/java/hyundai/movie_review/review/controller/ReviewController.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java
=> fix: 댓글 페이지네이션

src/main/java/hyundai/movie_review/comment/dto/CommentGetResponse.java, src/main/java/hyundai/movie_review/comment/service/CommentService.java, src/main/java/hyundai/movie_review/review/service/ReviewService.java
- close #108
댓글 조회 시 현재 사용자가 댓글 작성자인지 체크한 값 추가
=> fix: 댓글 작성자 여부 조회 추가

src/main/java/hyundai/movie_review/tag/service/TagService.java
=> refactor: 중복으로 태그가 들어가는 버그 수정

src/main/java/hyundai/movie_review/review/entity/Review.java
=> refactor: review 엔티티 조회 시, deleted false인 값만 가져오도록 수정

src/main/java/hyundai/movie_review/logout/controller/LogoutController.java
=> feat: logout 컨트롤러 구현

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: domain 수정

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: logout 도메인 수정

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: 쿠키 설정 재설정

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: redirec url 설정

src/main/java/hyundai/movie_review/member/controller/MemberController.java
=> refactor: redirect 제거

src/main/java/hyundai/movie_review/alarm/controller/AlarmController.java, src/main/java/hyundai/movie_review/alarm/repository/AlarmRepository.java, src/main/java/hyundai/movie_review/alarm/service/AlarmService.java
=> feat: 사용자가 읽지않은 모든 알림을 처리하는 기능 구현

src/main/java/hyundai/movie_review/member/repository/MemberRepositoryImpl.java
=> refactor: 점수, 리뷰, 댓글이 같을 경우 totalScore가 높은 순으로 정렬 개선

src/main/java/hyundai/movie_review/member/entity/Member.java, src/main/java/hyundai/movie_review/member/repository/MemberRepositoryImpl.java, src/main/java/hyundai/movie_review/ranking/dto/MemberRankingInfoDto.java
=> refactor: 랭킹 페이지에서, 내가 받은 좋아요를 기준으로 정렬되도록 수정

src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustom.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustomImpl.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java
- close #114
멤버가 본 영화를 추천에서 제외
=> fix: 멤버가 리뷰한 영화 추천에서 제외

src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustom.java, src/main/java/hyundai/movie_review/movie/repository/MovieRepositoryCustomImpl.java, src/main/java/hyundai/movie_review/movie/service/MovieService.java
=> refactor: 영화 추천 시, 사용자가 리뷰를 작성한 영화는 노출되지 않도록 변경

src/main/java/hyundai/movie_review/member/entity/Member.java
=> refactor: member profile image 수정

src/main/java/hyundai/movie_review/badge/event/BadgeEventListener.java, src/main/java/hyundai/movie_review/score/ScoreEventListener.java
=> refactor: date time formatter를 이용한 알람 메세지 수정
